import type { Metadata } from "next";
import { Inter} from "next/font/google";
import { TRPCReactProvider } from "@/trpc/client";
import "./globals.css";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter2 = Inter({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
      <html lang="en">
        <body
          className={`${inter.variable} ${inter2.variable} antialiased`}
          suppressHydrationWarning
        >
          {children}
        </body>
      </html>
    </TRPCReactProvider>
  );
}
